# Generated by Django 6.0.1 on 2026-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('audience', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('headline', models.TextField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField()),
                ('cta', models.TextField()),
                ('image_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
