# Generated by Django 6.0.1 on 2026-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='caption',
        ),
        migrations.AddField(
            model_name='campaign',
            name='generated_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
